#!/usr/bin/env python3
"""gen_roadkit_godot_fields.py -- writes addons/road_kit/road_kit_fields.gd from point_model's tables.

ONE declaration of every authored field lives in `point_model.POINT_FIELDS` / `ROAD_FIELDS`. The
Godot plugin (PLAN.md 3.1 option B) needs the same table to build its inspector and to read and
write `.roads.json`, and a hand-copied second table is exactly the drift the kit's own field-table
rule exists to stop. So it is GENERATED, and `--check` fails when the checked-in file is stale
(run it from the gate).

    python3 blender/tools/gen_roadkit_godot_fields.py           # write
    python3 blender/tools/gen_roadkit_godot_fields.py --check   # exit 1 if stale
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
BP = os.path.dirname(HERE)
REPO = os.path.dirname(BP)
sys.path.insert(0, os.path.join(BP, "addons", "road_kit_authoring"))
sys.path.insert(0, os.path.join(BP, "lib"))
import point_model as pm  # noqa: E402
import point_record_ops as ro  # noqa: E402

OUT = os.path.join(REPO, "addons", "road_kit", "road_kit_fields.gd")


def _lit(v):
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, float):
        return repr(v)
    if isinstance(v, int):
        return str(v)
    return '"%s"' % v


def _table(fields):
    rows = []
    for name, kind, default in fields:
        if isinstance(kind, tuple):
            rows.append('\t["%s", "e", %s, [%s]],' % (name, _lit(default), ", ".join('"%s"' % k for k in kind)))
        else:
            rows.append('\t["%s", "%s", %s, []],' % (name, kind, _lit(default)))
    return "\n".join(rows)


def render():
    return """@tool
extends RefCounted
## GENERATED by blender/tools/gen_roadkit_godot_fields.py from point_model.POINT_FIELDS / ROAD_FIELDS.
## Do not edit: change the kit's table and regenerate. Rows are [name, kind, default, enum_values];
## kind is i int, f float, b bool, s string, e enum (stored as its identifier string).

const SCHEMA_VER := %d
const DELTA_FIELDS := [%s]
const LINK_TYPES := [%s]
const ROLES := [%s]
## A point turned further than this from the facing the tool gave it was ROTATED by hand -- the bend
## gesture (`point_model.was_rotated`).
const ROTATED_TOL_DEG := %r
## Apply Cross-Section's field groups (`point_record_ops.MASK_GROUPS`).
const MASK_GROUPS := [%s]

const POINT_FIELDS := [
%s
]

const ROAD_FIELDS := [
%s
]
""" % (pm.SCHEMA_VER, ", ".join('"%s"' % f for f in pm.DELTA_FIELDS),
       ", ".join('"%s"' % t for t in pm.LINK_TYPES), ", ".join('"%s"' % r for r in pm.ROLES),
       float(pm.ROTATED_TOL_DEG), ", ".join('"%s"' % g for g in sorted(ro.MASK_GROUPS)),
       _table(pm.POINT_FIELDS), _table(pm.ROAD_FIELDS))


def main():
    text = render()
    if "--check" in sys.argv:
        cur = open(OUT).read() if os.path.exists(OUT) else ""
        if cur != text:
            print("road_kit_fields.gd is STALE -- run blender/tools/gen_roadkit_godot_fields.py")
            return 1
        print("road_kit_fields.gd is current")
        return 0
    with open(OUT, "w") as fh:
        fh.write(text)
    print("wrote", OUT)
    return 0


if __name__ == "__main__":
    sys.exit(main())
