@tool
extends RefCounted
## GENERATED by blender/tools/gen_roadkit_godot_fields.py from point_model.POINT_FIELDS / ROAD_FIELDS.
## Do not edit: change the kit's table and regenerate. Rows are [name, kind, default, enum_values];
## kind is i int, f float, b bool, s string, e enum (stored as its identifier string).

const SCHEMA_VER := 1
const DELTA_FIELDS := ["lanes_fwd", "lanes_bwd", "aux_fwd", "aux_bwd"]
const LINK_TYPES := ["SEGMENT", "JUNCTION", "AUX"]
const ROLES := ["SEGMENT", "INTERSECTION", "RAMP_ENTRY", "RAMP_EXIT", "TERMINUS", "RAMP"]

const POINT_FIELDS := [
	["uid", "s", "", []],
	["role", "e", "SEGMENT", ["SEGMENT", "INTERSECTION", "RAMP_ENTRY", "RAMP_EXIT", "TERMINUS", "RAMP"]],
	["schema_ver", "i", 1, []],
	["profile_mode", "e", "INHERIT", ["INHERIT", "OVERRIDE"]],
	["lanes_fwd", "i", 2, []],
	["lanes_bwd", "i", 2, []],
	["lane_width", "f", 4.5, []],
	["drop_side_fwd", "e", "KERB", ["KERB", "MEDIAN"]],
	["drop_side_bwd", "e", "KERB", ["KERB", "MEDIAN"]],
	["aux_fwd", "i", 0, []],
	["aux_bwd", "i", 0, []],
	["aux_side", "e", "KERB", ["KERB", "MEDIAN"]],
	["shoulder_left_width", "f", 0.0, []],
	["shoulder_right_width", "f", 0.0, []],
	["parking_left_width", "f", 0.0, []],
	["parking_right_width", "f", 0.0, []],
	["median_width", "f", 0.0, []],
	["left_kerb_height", "f", 0.15, []],
	["left_walk_width", "f", 0.0, []],
	["right_kerb_height", "f", 0.15, []],
	["right_walk_width", "f", 0.0, []],
	["design_speed", "f", 50.0, []],
	["deck_thickness", "f", 0.8, []],
	["pillar_spacing", "f", 30.0, []],
	["pillar_skip", "b", false, []],
	["pillar_offset", "f", 0.0, []],
	["ground_z", "f", 0.0, []],
	["has_ground_z", "b", false, []],
	["tangent_mode", "e", "AUTO", ["AUTO", "SHARP", "MANUAL"]],
	["handle_in", "f", 0.0, []],
	["handle_out", "f", 0.0, []],
	["roll", "f", 0.0, []],
	["fillet_radius", "f", 6.0, []],
	["allow_cross", "b", true, []],
	["allow_uturn", "b", false, []],
	["traffic_light", "b", false, []],
	["setback_solved", "f", 0.0, []],
	["setback_locked", "b", false, []],
]

const ROAD_FIELDS := [
	["name", "s", "", []],
	["road_class", "s", "street", []],
	["zone_id", "s", "", []],
	["is_loop", "b", false, []],
	["ped_access", "b", true, []],
	["barrier_height", "f", 1.0, []],
	["taper_factor", "f", 1.0, []],
	["median_style", "e", "RAISED", ["NONE", "PAINT_DOUBLE_Y", "RAISED", "WALL"]],
	["surface_mat", "s", "", []],
	["median_mat", "s", "", []],
	["deck_mat", "s", "", []],
	["kerb_mat", "s", "", []],
	["footway_mat", "s", "", []],
	["barrier_mat", "s", "", []],
	["mark_w_mat", "s", "", []],
	["mark_y_mat", "s", "", []],
	["surface_asset", "s", "", []],
	["median_asset", "s", "", []],
	["kerb_asset", "s", "", []],
	["footway_asset", "s", "", []],
	["barrier_asset", "s", "", []],
	["markings", "b", true, []],
]
