#!/usr/bin/env python3
"""library_status.py -- which library piece still needs an artist, and where every one of them came from.

    python3 tools/building_kit/library_status.py [--check]

The user's ask (2026-09-25): "centralize assets, such as toilet / counter / food, as Blender objects, so artists know
which one need to hand model / replace; and ensure all generated models come from CC0 / MIT or a licence that can be
open source / commercial, credited accordingly". The pieces ARE already central (`kits/library/library.blend`, one
collection each); what was missing is one place that says, per piece, what state it is in. This writes it:
`assets/world_source/kits/library/PIECES.md`, a table built from

* `pieces.json`   -- every piece the kit exports (its category and size);
* `extract.json`  -- the 23 base meshes cut from elbolilloduro's packs (CC0 models; their textures are NOT used),
                     each with its Japan review (`jp.status`: ok / refit / modeller);
* `library_procedural.py` / `library_landmarks.py` -- the pieces this project models in code (ours, MIT);
* `status.json`   -- what a PERSON says: an artist sets a piece to `"hand modelled"` when the real model is in (with
                     `by` and, for a bought/downloaded model, `source` + `licence`). Text, so it diffs and reviews.

A piece's status, in order: `status.json` if it names one; a base mesh whose Japan review asks for a modeller ->
"placeholder: needs a modeller"; any other base mesh -> "base mesh (adapted)"; a code-built piece -> "placeholder:
code-built". The licence column is derived the same way, and `--check` fails when a piece has NO known source (a
model someone dropped into the kit without recording where it came from) or when `PIECES.md` is stale.
"""
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, "..", ".."))
LIB = os.path.join(ROOT, "assets", "world_source", "kits", "library")
OUT = os.path.join(LIB, "PIECES.md")
STATUS = os.path.join(LIB, "status.json")
CODE = {"library_procedural.py": os.path.join(ROOT, "blender", "tools", "library_procedural.py"),
        "library_landmarks.py": os.path.join(ROOT, "blender", "tools", "library_landmarks.py")}
PACKS = {"6twelve": "6TWELVE", "gas": "Gas Station", "metro": "Metro", "burgerpiz": "BurgerPiz", "busstop": "Bus Stop"}


def code_pieces():
    """{piece name: source file} for every piece the code builds: a quoted CamelCase_Name in its source."""
    out = {}
    for fname, path in CODE.items():
        if not os.path.exists(path):
            continue
        for m in re.finditer(r'"([A-Z][A-Za-z0-9]*(?:_[A-Za-z0-9]+)*)"', open(path).read()):
            out.setdefault(m.group(1), fname)
    return out


def rows():
    pieces = json.load(open(os.path.join(LIB, "pieces.json")))["pieces"]
    extract = {p["name"]: p for p in json.load(open(os.path.join(LIB, "extract.json")))["pieces"]}
    status = json.load(open(STATUS)).get("pieces", {}) if os.path.exists(STATUS) else {}
    code = code_pieces()
    out, unknown = [], []
    for name in sorted(pieces):
        p = pieces[name]
        size = " x ".join("%.2f" % v for v in p.get("size", []))
        st = status.get(name, {})
        if name in extract:
            e = extract[name]
            jp = (e.get("jp") or {}).get("status", "")
            src = "base mesh from elbolilloduro *%s* (cut, resized, re-textured)" % PACKS.get(e.get("src"), e.get("src"))
            lic = "model CC0 1.0 (pack textures NOT used); changes MIT"
            state = "placeholder: needs a modeller" if jp in ("hand", "modeller") else \
                "base mesh (adapted, Japan review: %s)" % (jp or "none")
            note = (e.get("jp") or {}).get("note", "")
        elif name in code:
            src = "built in code (`blender/tools/%s`)" % code[name]
            lic = "ours, MIT"
            state = "placeholder: code-built"
            note = ""
        else:
            src, lic, state, note = "UNKNOWN", "UNKNOWN", "UNKNOWN", ""
            unknown.append(name)
        if st.get("status"):
            state = st["status"] + (" (by %s)" % st["by"] if st.get("by") else "")
        if st.get("source"):
            src = st["source"]
        if st.get("licence"):
            lic = st["licence"]
        if st.get("note"):
            note = st["note"]
        out.append((p.get("category", ""), name, size, state, src, lic, note))
    return out, unknown


def render(rs):
    todo = sum(1 for r in rs if r[3].startswith("placeholder"))
    lines = [
        "# library.blend -- every piece, its state and its source",
        "",
        "GENERATED by `tools/building_kit/library_status.py` from `pieces.json`, `extract.json`, the code that builds",
        "pieces and `status.json`. Do not edit this file: when you finish a real model of a piece, set it in",
        "`status.json` (`{\"pieces\": {\"Shop_Counter\": {\"status\": \"hand modelled\", \"by\": \"<you>\"}}}` -- and for a",
        "bought or downloaded model, `source` and `licence`) and re-run the tool. Only CC0 / MIT / CC BY (credited in",
        "`CREDITS.md`) sources may enter the repo -- see `assets/LICENCE_AUDIT.md`.",
        "",
        "**%d of %d pieces are placeholders** (a code-built block, or a base mesh whose Japan review asks for a modeller)."
        % (todo, len(rs)),
        "",
        "| category | piece | size (m, x y z) | state | source | licence | note |",
        "|---|---|---|---|---|---|---|",
    ]
    for cat, name, size, state, src, lic, note in sorted(rs, key=lambda r: (not r[3].startswith("placeholder"),
                                                                             r[0], r[1])):
        lines.append("| %s | `%s` | %s | %s | %s | %s | %s |" % (cat, name, size, state, src, lic,
                                                               note.replace("|", "/")))
    return "\n".join(lines) + "\n"


def main(argv):
    rs, unknown = rows()
    text = render(rs)
    stale = not os.path.exists(OUT) or open(OUT).read() != text
    if "--check" in argv:
        for n in unknown:
            print("library_status: %s has NO recorded source -- say where it came from in status.json" % n)
        if stale:
            print("library_status: PIECES.md is stale -- run tools/building_kit/library_status.py")
        sys.exit(1 if unknown or stale else 0)
    if stale:
        open(OUT, "w").write(text)
    print("library_status: %d pieces, %d placeholders, %d with no recorded source%s"
          % (len(rs), sum(1 for r in rs if r[3].startswith("placeholder")), len(unknown),
             (" (" + ", ".join(unknown) + ")") if unknown else ""))


if __name__ == "__main__":
    main(sys.argv[1:])
