package com.openworld.debug;

import com.openworld.character.AICharacter;
import com.openworld.character.Character;
import com.openworld.character.CharacterInfo;
import com.openworld.character.Health;
import com.openworld.character.Player;
import com.openworld.net.NetStats;
import com.openworld.net.NetworkManager;
import com.openworld.weapon.FirearmItem;
import com.openworld.weapon.WeaponController;
import com.openworld.weapon.WeaponItem;
import com.openworld.world.manager.ImpactManager;
import godot.annotation.Register;
import godot.annotation.Script;
import godot.api.BoxShape3D;
import godot.api.CollisionShape3D;
import godot.api.Input;
import godot.api.Node;
import godot.api.Node3D;
import godot.api.OS;
import godot.api.PackedScene;
import godot.api.StaticBody3D;
import godot.core.NodePath;
import godot.core.StringName;
import godot.core.Vector3;
import godot.global.GD;

import java.util.List;

/**
 * Two-instance headless check for PLAN.md N1 — one seeded MSG_SHOT per trigger pull, validated and
 * regenerated by the host. Run as TWO processes of the same scene ({@code tools/net/run_net_shot_test.sh}):
 *
 * <pre>
 *   godot --headless --path . res://src/main/resources/com/openworld/debug/NetShotTest.tscn -- --role=host
 *   godot --headless --path . res://src/main/resources/com/openworld/debug/NetShotTest.tscn -- --role=client
 * </pre>
 *
 * <p>The HOST spawns a static target (an AICharacter whose brain is a {@link ScriptedInputController},
 * so it stands still) and a backstop wall; the joining client's body gets an SG1 from
 * the scene's pickup, which the client's body walks onto — the host-arbitrated pickup request is
 * the real path (a host-side {@code requestEquip} onto an OWNED body is refused by the client's
 * inventory reconciliation, {@code inventory_owned_no_resurrect}).
 * The CLIENT aims its own body's view at the target and pulls the trigger through the {@code Input}
 * singleton, so the shipped {@code PlayerController → WeaponController → FirearmItem} path is what runs.
 *
 * <p>Both sides print one {@code [shot]} line per pull with the per-pellet hit names: the client's
 * prediction and the host's resolution of the same pull. The script compares them and the counters:
 * {@code shot_sent} must equal the number of pulls (ONE message per pull, not one per pellet), every
 * pull must be {@code shot_accepted}, and the host's pellet hits must match the client's.
 */
@Script(className = "NetShotTestHost")
public class NetShotTestHost extends Node3D {

    private static final int PORT = 7791;
    private static final String TARGET_ID = "netshot-target";
    private static final String PLAYER_SCENE = "res://src/main/resources/com/openworld/character/Player.tscn";
    private static final String AI_SCENE = "res://src/main/resources/com/openworld/character/AICharacter.tscn";
    /** Where NetShotTest.tscn places the SG1 pickup — the client walks its body onto it. */
    private static final Vector3 PICKUP_AT = new Vector3(0, 1.0, 6);
    private static final int PULLS = 10;
    private static final double TIMEOUT_S = 90.0;

    private boolean host;
    private double clock;
    private NetworkManager net;

    // host
    private boolean sawClient;
    private double clientGoneAt = -1;
    private Health targetHealth;
    private float targetHpStart;

    // client
    private int pullsDone;
    private double nextPullAt = -1;
    private int releaseInFrames = -1;
    private List<String> lastSeenHits;
    private double doneAt = -1;

    @Register
    @Override
    public void _ready() {
        for (String a : OS.INSTANCE.getCmdlineUserArgs()) {
            if (a.equals("--role=host")) host = true;
        }
        Node n = getNodeOrNull("/root/NetworkManager");
        net = n instanceof NetworkManager nm ? nm : null;
        net.debugShots = true;

        buildGround();
        if (getTree().getFirstNodeInGroup("impact_manager") == null) addChild(new ImpactManager());

        if (host) {
            spawnTarget();
            net.hostServer(PORT);
        } else {
            net.joinServer("127.0.0.1", PORT);
        }
        GD.print("[netshot] role=" + (host ? "host" : "client"));
    }

    private void buildGround() {
        box("Ground", new Vector3(200, 1, 200), new Vector3(0, -0.5, 0));
        box("Backstop", new Vector3(30, 12, 1), new Vector3(0, 6, -30));
    }

    private void box(String name, Vector3 size, Vector3 pos) {
        StaticBody3D b = new StaticBody3D();
        b.setName(name);
        CollisionShape3D cs = new CollisionShape3D();
        BoxShape3D shape = new BoxShape3D();
        shape.setSize(size);
        cs.setShape(shape);
        b.addChild(cs);
        addChild(b);
        b.setGlobalPosition(pos);
    }

    private Node characters() { return getNodeOrNull("Characters"); }

    private void spawnTarget() {
        if (!(GD.INSTANCE.load(AI_SCENE) instanceof PackedScene ps)) return;
        if (!(ps.instantiate() instanceof AICharacter ai)) return;
        CharacterInfo info = new CharacterInfo();
        info.characterId = TARGET_ID;
        info.displayName = "Target";
        info.faction = "neutral";
        ai.characterInfo = info;
        ai.setPosition(new Vector3(0, 0.1, -12));
        characters().addChild(ai);
        ScriptedInputController still = new ScriptedInputController();
        still.setName("StillController");
        ai.attachController(still);
        if (ai.getNodeOrNull(new NodePath("Health")) instanceof Health h) {
            h.maxHealth = 100000f;
            h.resetFull();
            targetHealth = h;
            targetHpStart = h.getCurrentHealth();
        }
    }

    @Register
    @Override
    public void _physicsProcess(double delta) {
        clock += delta;
        if (clock > TIMEOUT_S) finish("TIMEOUT");
        if (host) hostStep(); else clientStep();
    }

    private Player remotePlayer() {
        for (Node node : getTree().getNodesInGroup(new StringName("characters"))) {
            if (node instanceof Player p && p.characterInfo != null && p.characterInfo.ownerPeerId != 1) return p;
        }
        return null;
    }

    private void hostStep() {
        Player p = remotePlayer();
        if (p != null) {
            sawClient = true;
        } else if (sawClient && clientGoneAt < 0) {
            clientGoneAt = clock;
        }
        if (clientGoneAt >= 0 && clock - clientGoneAt > 1.0) finish("client left");
    }

    private void clientStep() {
        Player me = null;
        for (Node node : getTree().getNodesInGroup(new StringName("characters"))) {
            if (node instanceof Player p && p.characterInfo != null && net.isAuthorityFor(p.characterInfo)) me = p;
        }
        Node3D target = null;
        for (Node node : getTree().getNodesInGroup(new StringName("characters"))) {
            if (node instanceof Character c && c.characterInfo != null && TARGET_ID.equals(c.characterInfo.characterId)) {
                target = c;
            }
        }
        if (me == null || target == null || !(findWeaponController(me) instanceof WeaponController wc)) return;

        // Face the view onto the target's chest (world yaw, positive pitch up — ControlRotation W3).
        Vector3 eye = me.getGlobalPosition().plus(new Vector3(0, 1.5, 0));
        Vector3 to = target.getGlobalPosition().plus(new Vector3(0, 1.1, 0)).minus(eye);
        me.controlRotation.yaw = Math.toDegrees(Math.atan2(-to.getX(), -to.getZ()));
        me.controlRotation.pitch = Math.toDegrees(Math.atan2(to.getY(), Math.hypot(to.getX(), to.getZ())));

        FirearmItem sg = null;
        int sgSlot = -1;
        for (int i = 0; i < wc.getSlotCount(); i++) {
            if (wc.getWeaponItem(i) instanceof FirearmItem f && f.pelletCount > 1) { sg = f; sgSlot = i; }
        }
        if (sg == null) {
            // Collect the scene's SG1 the way a player does: stand on it. The owning client moves its own
            // body (the host follows the snapshot), and the pickup request is host-arbitrated.
            if (me.getGlobalPosition().distanceTo(PICKUP_AT) > 0.6) me.setGlobalPosition(PICKUP_AT);
            return;
        }
        if (wc.getCurrentWeaponItem() != sg) {
            if (!wc.isWeaponTransitioning()) wc.onSetWeapon(sgSlot);
            return;
        }
        if (nextPullAt < 0) nextPullAt = clock + 1.5;   // let the draw and the aim settle

        if (sg.lastShotPelletHits != lastSeenHits && !sg.lastShotPelletHits.isEmpty()) {
            lastSeenHits = sg.lastShotPelletHits;
            GD.print("[shot] client predicted #" + (pullsDone - 1) + " -> " + lastSeenHits);
        }
        if (releaseInFrames >= 0 && --releaseInFrames < 0) Input.INSTANCE.actionRelease(new StringName("fire"));
        if (pullsDone < PULLS && clock >= nextPullAt && releaseInFrames < 0) {
            sg.setMagazine(Math.max(sg.getMagazine(), 4));
            Input.INSTANCE.actionPress(new StringName("fire"), 1.0f);
            releaseInFrames = 3;
            pullsDone++;
            nextPullAt = clock + 0.9;
        }
        if (pullsDone >= PULLS && doneAt < 0) doneAt = clock;
        if (doneAt >= 0 && clock - doneAt > 2.0) finish("pulls done");
    }

    private static Node findWeaponController(Node body) {
        return body.getNodeOrNull(new NodePath("WeaponController"));
    }

    private boolean finished;

    private void finish(String why) {
        if (finished) return;
        finished = true;
        StringBuilder sb = new StringBuilder("[netshot] SUMMARY role=" + (host ? "host" : "client") + " (" + why + ")");
        for (String k : new String[] {"shot_sent", "shot_accepted", "shot_invalid", "shot_slot_mismatch",
                "shot_slot_fallback", "shot_rejected_stale_seq", "shot_rejected_too_fast",
                "shot_rejected_origin_too_far", "shot_rejected_aim_diverged", "shot_rejected_spread_too_narrow",
                "drop_rate_limited"}) {
            sb.append(' ').append(k).append('=').append(NetStats.get(k));
        }
        if (host && targetHealth != null) {
            sb.append(String.format(" target_damage=%.1f", targetHpStart - targetHealth.getCurrentHealth()));
        }
        if (!host) sb.append(" pulls=").append(pullsDone);
        GD.print(sb.toString());
        getTree().quit();
    }
}
