package com.openworld.debug;

import com.openworld.character.AICharacter;
import com.openworld.character.Character;
import com.openworld.character.CharacterInfo;
import com.openworld.character.Health;
import com.openworld.character.Player;
import com.openworld.net.NetStats;
import com.openworld.net.NetworkManager;
import com.openworld.weapon.FirearmItem;
import com.openworld.weapon.WeaponController;
import com.openworld.weapon.WeaponItem;
import com.openworld.world.manager.ImpactManager;
import godot.annotation.Register;
import godot.annotation.Script;
import godot.api.BoxShape3D;
import godot.api.CollisionShape3D;
import godot.api.Input;
import godot.api.Node;
import godot.api.Node3D;
import godot.api.OS;
import godot.api.PackedScene;
import godot.api.StaticBody3D;
import godot.core.NodePath;
import godot.core.StringName;
import godot.core.Vector3;
import godot.global.GD;

import java.util.List;

/**
 * Two-instance headless check for PLAN.md N1 — one seeded MSG_SHOT per trigger pull, validated and
 * regenerated by the host. Run as TWO processes of the same scene ({@code tools/net/run_net_shot_test.sh}):
 *
 * <pre>
 *   godot --headless --path . res://src/main/resources/com/openworld/debug/NetShotTest.tscn -- --role=host
 *   godot --headless --path . res://src/main/resources/com/openworld/debug/NetShotTest.tscn -- --role=client
 * </pre>
 *
 * <p>The HOST spawns a static target (an AICharacter whose brain is a {@link ScriptedInputController},
 * so it stands still) and a backstop wall; the joining client's body gets an SHG1 from
 * the scene's pickup, which the client's body walks onto — the host-arbitrated pickup request is
 * the real path (a host-side {@code requestEquip} onto an OWNED body is refused by the client's
 * inventory reconciliation, {@code inventory_owned_no_resurrect}).
 * The CLIENT aims its own body's view at the target and pulls the trigger through the {@code Input}
 * singleton, so the shipped {@code PlayerController → WeaponController → FirearmItem} path is what runs.
 *
 * <p>Both sides print one {@code [shot]} line per pull with the per-pellet hit names: the client's
 * prediction and the host's resolution of the same pull. The script compares them and the counters:
 * {@code shot_sent} must equal the number of pulls (ONE message per pull, not one per pellet), every
 * pull must be {@code shot_accepted}, and the host's pellet hits must match the client's.
 */
@Script(className = "NetShotTestHost")
public class NetShotTestHost extends Node3D {

    private static final int PORT = 7791;
    private static final String TARGET_ID = "netshot-target";
    private static final String PLAYER_SCENE = "res://src/main/resources/com/openworld/character/Player.tscn";
    private static final String AI_SCENE = "res://src/main/resources/com/openworld/character/AICharacter.tscn";
    /** Where NetShotTest.tscn places the SHG1 pickup — the client walks its body onto it. */
    private static final Vector3 PICKUP_AT = new Vector3(0, 1.0, 6);
    private static final int PULLS = 10;
    private static final double TIMEOUT_S = 110.0;

    private boolean host;
    /** A third peer that only watches: does it see the client's shots as real pellets (N1b)? */
    private boolean observer;
    private boolean dropResults;
    private boolean wasConnected;
    private double clock;
    private NetworkManager net;

    // host
    private boolean sawClient;
    private double clientGoneAt = -1;
    private Health targetHealth;
    private long lastSeenShotCount;
    private double lastShotAt;
    private float targetHpStart;

    // client
    private int pullsDone;
    private double nextPullAt = -1;
    private int releaseInFrames = -1;
    private List<String> lastSeenHits;
    private double doneAt = -1;

    @Register
    @Override
    public void _ready() {
        for (String a : OS.INSTANCE.getCmdlineUserArgs()) {
            if (a.equals("--role=host")) host = true;
            if (a.equals("--role=observer")) observer = true;
            if (a.equals("--drop-results")) dropResults = true;
        }
        Node n = getNodeOrNull("/root/NetworkManager");
        net = n instanceof NetworkManager nm ? nm : null;
        net.debugShots = true;
        net.debugDropShotResults = dropResults;

        buildGround();
        if (getTree().getFirstNodeInGroup("impact_manager") == null) addChild(new ImpactManager());
        if (getNodeOrNull("/root/EventBus") instanceof com.openworld.game.EventBus bus) {
            bus.damageDealt.connectUnsafe(godot.core.MethodCallable.createUnsafe(this, "onDamageDealt"),
                    godot.api.Object.ConnectFlags.DEFAULT);
        }

        if (host) {
            spawnTarget();
            net.hostServer(PORT);
        } else {
            net.joinServer("127.0.0.1", PORT);
        }
        GD.print("[netshot] role=" + role());
    }

    private void buildGround() {
        box("Ground", new Vector3(200, 1, 200), new Vector3(0, -0.5, 0));
        box("Backstop", new Vector3(30, 12, 1), new Vector3(0, 6, -30));
    }

    private void box(String name, Vector3 size, Vector3 pos) {
        StaticBody3D b = new StaticBody3D();
        b.setName(name);
        CollisionShape3D cs = new CollisionShape3D();
        BoxShape3D shape = new BoxShape3D();
        shape.setSize(size);
        cs.setShape(shape);
        b.addChild(cs);
        addChild(b);
        b.setGlobalPosition(pos);
    }

    private Node characters() { return getNodeOrNull("Characters"); }

    private void spawnTarget() {
        if (!(GD.INSTANCE.load(AI_SCENE) instanceof PackedScene ps)) return;
        if (!(ps.instantiate() instanceof AICharacter ai)) return;
        CharacterInfo info = new CharacterInfo();
        info.characterId = TARGET_ID;
        info.displayName = "Target";
        info.faction = "neutral";
        ai.characterInfo = info;
        ai.setPosition(new Vector3(0, 0.1, -12));
        characters().addChild(ai);
        ScriptedInputController still = new ScriptedInputController();
        still.setName("StillController");
        ai.attachController(still);
        if (ai.getNodeOrNull(new NodePath("Health")) instanceof Health h) {
            h.maxHealth = 100000f;
            h.resetFull();
            targetHealth = h;
            targetHpStart = h.getCurrentHealth();
        }
    }

    @Register
    @Override
    public void _physicsProcess(double delta) {
        clock += delta;
        if (clock > TIMEOUT_S) finish("TIMEOUT");
        if (host) hostStep(); else if (observer) observerStep(); else clientStep();
    }

    private String role() {
        return host ? "host" : observer ? (dropResults ? "observer-drop" : "observer") : "client";
    }

    /** Stand out of the line of fire and watch; finish when the host goes away. */
    private void observerStep() {
        if (net.isNetworked() && clock > 1.0) wasConnected = true;
        for (Node node : getTree().getNodesInGroup(new StringName("characters"))) {
            if (node instanceof Player p && p.characterInfo != null && net.isAuthorityFor(p.characterInfo)) {
                Vector3 spot = new Vector3(dropResults ? -15 : 15, 1.0, 10);
                if (p.getGlobalPosition().distanceTo(spot) > 1.0) p.setGlobalPosition(spot);
            }
        }
        if (wasConnected && !net.isNetworked()) finish("host left");
    }

    private Player remotePlayer() {
        for (Node node : getTree().getNodesInGroup(new StringName("characters"))) {
            if (node instanceof Player p && p.characterInfo != null && p.characterInfo.ownerPeerId != 1) return p;
        }
        return null;
    }

    private void hostStep() {
        Player p = remotePlayer();
        if (p != null) {
            sawClient = true;
        } else if (sawClient && clientGoneAt < 0) {
            clientGoneAt = clock;
        }
        if (clientGoneAt >= 0 && clock - clientGoneAt > 1.0) finish("client left");
        long seen = NetStats.get("shot_accepted") + NetStats.get("shot_rejected_stale_seq")
                + NetStats.get("shot_rejected_too_fast") + NetStats.get("shot_rejected_origin_too_far")
                + NetStats.get("shot_rejected_aim_diverged") + NetStats.get("shot_rejected_spread_too_narrow");
        if (seen != lastSeenShotCount) { lastSeenShotCount = seen; lastShotAt = clock; }
        if (seen >= PULLS + 10 && clock - lastShotAt > 3.0) finish("client done");
    }

    private void clientStep() {
        Player me = null;
        for (Node node : getTree().getNodesInGroup(new StringName("characters"))) {
            if (node instanceof Player p && p.characterInfo != null && net.isAuthorityFor(p.characterInfo)) me = p;
        }
        Node3D target = null;
        for (Node node : getTree().getNodesInGroup(new StringName("characters"))) {
            if (node instanceof Character c && c.characterInfo != null && TARGET_ID.equals(c.characterInfo.characterId)) {
                target = c;
            }
        }
        if (me == null || target == null || !(findWeaponController(me) instanceof WeaponController wc)) return;

        // Face the view onto the target's chest (world yaw, positive pitch up — ControlRotation W3).
        Vector3 eye = me.getGlobalPosition().plus(new Vector3(0, 1.5, 0));
        Vector3 to = target.getGlobalPosition().plus(new Vector3(0, 1.1, 0)).minus(eye);
        me.controlRotation.yaw = Math.toDegrees(Math.atan2(-to.getX(), -to.getZ()));
        me.controlRotation.pitch = Math.toDegrees(Math.atan2(to.getY(), Math.hypot(to.getX(), to.getZ())));

        FirearmItem sg = null;
        int sgSlot = -1;
        for (int i = 0; i < wc.getSlotCount(); i++) {
            if (wc.getWeaponItem(i) instanceof FirearmItem f && f.pelletCount > 1) { sg = f; sgSlot = i; }
        }
        if (sg == null) {
            // Collect the scene's SHG1 the way a player does: stand on it. The owning client moves its own
            // body (the host follows the snapshot), and the pickup request is host-arbitrated.
            if (me.getGlobalPosition().distanceTo(PICKUP_AT) > 0.6) me.setGlobalPosition(PICKUP_AT);
            return;
        }
        if (wc.getCurrentWeaponItem() != sg) {
            if (!wc.isWeaponTransitioning()) wc.onSetWeapon(sgSlot);
            return;
        }
        // Wait for the watching peers (N1b) — the script starts them after this client has the gun, so
        // their bodies cannot spawn onto the pickup — then let the draw and the aim settle.
        if (nextPullAt < 0) {
            int players = 0;
            for (Node node : getTree().getNodesInGroup(new StringName("characters"))) if (node instanceof Player) players++;
            if (players < 3) return;
            nextPullAt = clock + 2.0;
        }

        if (sg.lastShotPelletHits != lastSeenHits && !sg.lastShotPelletHits.isEmpty()) {
            lastSeenHits = sg.lastShotPelletHits;
            GD.print("[shot] client predicted #" + (pullsDone - 1) + " dirs " + sg.lastShotDirectionDigest
                    + " -> " + lastSeenHits);
        }
        if (releaseInFrames >= 0 && --releaseInFrames < 0) Input.INSTANCE.actionRelease(new StringName("fire"));
        if (pullsDone < PULLS && clock >= nextPullAt && releaseInFrames < 0) {
            sg.setMagazine(Math.max(sg.getMagazine(), 4));
            Input.INSTANCE.actionPress(new StringName("fire"), 1.0f);
            releaseInFrames = 3;
            pullsDone++;
            nextPullAt = clock + Math.max(0.9, sg.fireInterval() * 1.5);   // SHG1 fires once a second
        }
        if (pullsDone >= PULLS && doneAt < 0) doneAt = clock;
        if (doneAt >= 0) forgeStep(me, sgSlot, target);
    }

    /**
     * The CONTROL for the host's validation: after the honest pulls, send shots a buggy or forged client
     * could send, straight through {@code sendShot}, spaced so each one meets a refilled fire budget and
     * is refused for its own reason — then a burst the budget must cut. Without these the gate would pass
     * a host that accepts anything.
     */
    private void forgeStep(Player me, int slot, Node3D target) {
        String id = me.characterInfo.characterId;
        Vector3 origin = me.getGlobalPosition().plus(new Vector3(0, 1.2, 0));
        Vector3 aim = target.getGlobalPosition().plus(new Vector3(0, 1.1, 0)).minus(origin).normalized();
        double t = clock - doneAt;
        int step = (int) Math.floor((t - 2.0) / 1.6);   // one forged shot every 1.6 s after a 2 s settle
        if (t < 2.0 || step <= forgeStepDone) return;
        forgeStepDone = step;
        switch (step) {
            case 0 -> { net.sendShot(id, slot, 0, origin, aim, 4f); GD.print("[forge] replayed shotSeq 0"); }
            case 1 -> { net.sendShot(id, slot, 1000, origin.plus(new Vector3(10, 0, 0)), aim, 4f); GD.print("[forge] origin 10 m off"); }
            case 2 -> { net.sendShot(id, slot, 1001, origin, aim, 0f); GD.print("[forge] zero cone"); }
            case 3 -> { net.sendShot(id, slot, 1002, origin, aim.times(-1f), 4f); GD.print("[forge] aim reversed"); }
            case 4 -> {
                for (int i = 0; i < 6; i++) net.sendShot(id, slot, 1003 + i, origin, aim, 4f);
                GD.print("[forge] burst of 6");
            }
            case 6 -> finish("pulls + forgeries done");
            default -> { }
        }
    }

    private int forgeStepDone = -1;

    private static Node findWeaponController(Node body) {
        return body.getNodeOrNull(new NodePath("WeaponController"));
    }

    private boolean finished;

    private int hitConfirmedLocal = 0;

    /** 2.8 item 9: count host-confirmed hits credited to this peer's own player (the hit marker's input). */
    @Register
    public void onDamageDealt(String attackerId, float damage, boolean headshot, boolean killed) {
        for (com.openworld.character.Player p : com.openworld.game.PlayerRegistry.getPlayers()) {
            if (GD.isInstanceValid(p) && p.isLocalOwnedPlayer() && p.characterInfo != null
                    && attackerId.equals(p.characterInfo.characterId)) {
                hitConfirmedLocal++;
                return;
            }
        }
    }

    private void finish(String why) {
        if (finished) return;
        finished = true;
        StringBuilder sb = new StringBuilder("[netshot] SUMMARY role=" + role() + " (" + why + ")");
        for (String k : new String[] {"shot_sent", "shot_accepted", "shot_invalid", "shot_slot_mismatch",
                "shot_slot_fallback", "shot_rejected_stale_seq", "shot_rejected_too_fast",
                "shot_rejected_origin_too_far", "shot_rejected_aim_diverged", "shot_rejected_spread_too_narrow",
                "drop_rate_limited", "shot_result_batches_sent", "shot_result_received", "shot_result_tracer",
                "cue_fallback_tracer", "cue_tracer_superseded", "cue_tracer_waited_for_result"}) {
            sb.append(' ').append(k).append('=').append(NetStats.get(k));
        }
        if (host && targetHealth != null) {
            sb.append(String.format(" target_damage=%.1f", targetHpStart - targetHealth.getCurrentHealth()));
        }
        if (!host) sb.append(" pulls=").append(pullsDone);
        sb.append(" hit_confirmed_local=").append(hitConfirmedLocal);
        GD.print(sb.toString());
        getTree().quit();
    }
}
