package com.openworld.character;

import com.openworld.game.EventBus;
import com.openworld.carrier.vehicle.Vehicle;
import godot.annotation.RegisterClass;
import godot.annotation.RegisterFunction;
import godot.api.Node;
import godot.core.StringName;
import godot.core.StringNames;
import com.openworld.control.PlayerController;
import com.openworld.control.UserCommand;
import com.openworld.ui.HUDManager;

/**
 * Human-controlled character body.
 *
 * Input is generated by the PlayerController child node, not here.
 * This class owns only player-specific body hardware: the aimRay self-exclusion
 * (prevents self-hits), AimStayTimer node (used by PlayerController), the
 * EventBus death notification, and vehicle enter/exit logic.
 *
 * nearbyVehicle is set/cleared by Vehicle.onEntranceBodyEntered/Exited when
 * the player walks into or out of a vehicle's entrance trigger zone. When the
 * player presses "use" (enterExit in the command) and nearbyVehicle is set,
 * applyInput delegates to Vehicle.requestEnter(this) — direct seat in
 * single-player, host-arbitrated grant when networked — rather than processing
 * normal character inputs.
 */
@RegisterClass
public class Player extends Character {

    /** Set by the nearest Vehicle's EntranceArea when the player is in range. */
    public Vehicle nearbyVehicle;

    @RegisterFunction
    @Override
    public void _ready() {
        super._ready();
        aimRay.addException(this);
        // Deferred so all sibling _ready() calls (e.g. HUDManager) finish
        // connecting to playerSpawned before this fires.
        callDeferred(StringNames.toGodotName("emitPlayerSpawned"));
    }

    @RegisterFunction
    public void emitPlayerSpawned() {
        Node busNode = getNodeOrNull("/root/EventBus");
        if (busNode instanceof EventBus bus) bus.playerSpawned.emit(this);
    }

    @Override
    protected void applyInput(UserCommand cmd, double delta) {
        if (cmd.enterExit && nearbyVehicle != null) {
            // A destroyed vehicle is freed without firing its EntranceArea body_exited, so
            // this reference can dangle — calling into a freed object throws (Round 11 N3).
            if (!godot.global.GD.isInstanceValid(nearbyVehicle)) {
                nearbyVehicle = null;
            } else {
                // Host-arbitrated when networked (the seat change lands on the grant echo);
                // direct tryEnter in single-player — see Vehicle.requestEnter (Round 11 N3).
                nearbyVehicle.requestEnter(this);
                return; // skip normal inputs this tick
            }
        }
        super.applyInput(cmd, delta);
    }

    @RegisterFunction
    @Override
    public void onDied() {
        setProcessInput(false);
        super.onDied();
        Node eventBusNode = getNodeOrNull("/root/EventBus");
        if (eventBusNode instanceof EventBus bus) bus.playerDied.emit();
    }

    /**
     * Network death for the locally-owned player (Round 11 N2 — MSG_ELIMINATION): the host
     * owns our health, so our own death arrives over the wire instead of through
     * Health.applyDamage → onDied. Plays the shared death visuals and the player-death UI
     * signal, but NEVER drops weapons — death drops are host-announced (MSG_WEAPON_DROPPED)
     * and local drops here would duplicate them as orphan pickups. Idempotent via the
     * deathVisualsApplied guard.
     */
    @Override
    public void applyReplicatedDeath() {
        if (deathVisualsApplied) return;
        setProcessInput(false);
        super.applyReplicatedDeath();
        Node eventBusNode = getNodeOrNull("/root/EventBus");
        if (eventBusNode instanceof EventBus bus) bus.playerDied.emit();
    }
}
