package com.openworld.character;

import com.openworld.game.EventBus;
import com.openworld.game.PlayerRegistry;
import com.openworld.carrier.vehicle.Vehicle;
import godot.annotation.Register;
import godot.annotation.Script;
import godot.api.Node;
import godot.core.StringName;
import godot.core.StringNames;
import com.openworld.control.PlayerController;
import com.openworld.control.UserCommand;
import com.openworld.ui.HUDManager;

/**
 * Human-controlled character body.
 *
 * Input is generated by the PlayerController child node, not here.
 * This class owns only player-specific body hardware: the aimRay self-exclusion
 * (prevents self-hits), AimStayTimer node (used by PlayerController), the
 * EventBus death notification, and vehicle enter/exit logic.
 *
 * nearbyVehicle is set/cleared by Vehicle.onEntranceBodyEntered/Exited when
 * the player walks into or out of a vehicle's entrance trigger zone. When the
 * player presses "use" (enterExit in the command) and nearbyVehicle is set,
 * applyInput delegates to Vehicle.requestEnter(this) — direct seat in
 * single-player, host-arbitrated grant when networked — rather than processing
 * normal character inputs.
 */
@Script
public class Player extends Character {

    /** Set by the nearest Vehicle's EntranceArea when the player is in range. */
    public Vehicle nearbyVehicle;

    @Register
    @Override
    public void _ready() {
        super._ready();
        aimRay.addException(this);
        // Register with the player registry so AI LOD can find the nearest player in
        // O(playerCount) instead of scanning the whole "characters" group (PLAN.md Part D).
        PlayerRegistry.register(this);
        // Deferred so all sibling _ready() calls (e.g. HUDManager) finish
        // connecting to playerSpawned before this fires.
        callDeferred(StringNames.toGodotName("emitPlayerSpawned"));
    }

    /**
     * Deregister on leaving the tree (free/despawn). Deliberately NOT in onDied: the group
     * scan this replaces counted dead-but-still-present bodies too (it filtered on
     * {@code instanceof Player}, not liveness), so a downed player's ragdoll keeps holding
     * AIs near it ACTIVE until the body is actually freed — preserving prior LOD behaviour.
     */
    @Register
    @Override
    public void _exitTree() {
        PlayerRegistry.deregister(this);
        super._exitTree();
    }

    @Register
    public void emitPlayerSpawned() {
        Node busNode = getNodeOrNull("/root/EventBus");
        if (busNode instanceof EventBus bus) bus.playerSpawned.emit(this);
    }

    @Override
    protected void applyInput(UserCommand cmd, double delta) {
        // Seated passenger exit (multi-seat): the driver's exit runs through the vehicle's own
        // _physicsProcess, but a passenger's controller stays on this character — handle the
        // interact key here. Host-arbitrated like every other seat change.
        if (cmd.enterExit && isSeatedPassenger()
                && currentVehicleNode instanceof com.openworld.carrier.vehicle.Vehicle v
                && godot.global.GD.isInstanceValid(v)) {
            v.requestExitOccupant(this);
            return;
        }
        if (cmd.enterExit && nearbyVehicle != null) {
            // A destroyed vehicle is freed without firing its EntranceArea body_exited, so
            // this reference can dangle — calling into a freed object throws (Round 11 N3).
            if (!godot.global.GD.isInstanceValid(nearbyVehicle)) {
                nearbyVehicle = null;
            } else if (nearbyVehicle.isAiOccupied()) {
                // An AI-driven traffic car → carjack: host evicts the AI driver, then seats us
                // (PLAN.md I3c). Same Enter key as a normal entry.
                nearbyVehicle.requestCarjack(this);
                return; // skip normal inputs this tick
            } else {
                // Host-arbitrated when networked (the seat change lands on the grant echo);
                // direct tryEnter in single-player — see Vehicle.requestEnter (Round 11 N3).
                nearbyVehicle.requestEnter(this);
                return; // skip normal inputs this tick
            }
        }
        super.applyInput(cmd, delta);
    }

    @Register
    @Override
    public void onDied() {
        setProcessInput(false);
        super.onDied();
        Node eventBusNode = getNodeOrNull("/root/EventBus");
        if (eventBusNode instanceof EventBus bus) bus.playerDied.emit();
    }

    /**
     * Network death for the locally-owned player (Round 11 N2 — MSG_ELIMINATION): the host
     * owns our health, so our own death arrives over the wire instead of through
     * Health.applyDamage → onDied. Plays the shared death visuals and the player-death UI
     * signal, but NEVER drops weapons — death drops are host-announced (MSG_WEAPON_DROPPED)
     * and local drops here would duplicate them as orphan pickups. Idempotent via the
     * deathVisualsApplied guard.
     */
    @Override
    public void applyReplicatedDeath() {
        if (deathVisualsApplied) return;
        setProcessInput(false);
        super.applyReplicatedDeath();
        Node eventBusNode = getNodeOrNull("/root/EventBus");
        if (eventBusNode instanceof EventBus bus) bus.playerDied.emit();
    }

    // ── GPS waypoint (I5) ──────────────────────────────────────────────────────

    /** This player's network id, or "" before _ready stamps it. Used to key its WaypointStore entry. */
    private String waypointKey() {
        return characterInfo != null ? characterInfo.characterId : "";
    }

    /**
     * Set this player's GPS waypoint (from a full-map click): record it locally in the
     * {@link com.openworld.game.WaypointStore} and, when networked, broadcast it so teammates see the
     * marker in this player's faction colour. The minimap / full map / world-space arrow read the store.
     */
    public void setWaypoint(godot.core.Vector3 worldPos) {
        String id = waypointKey();
        if (id.isEmpty() || worldPos == null) return;
        com.openworld.game.WaypointStore.set(id, worldPos);
        Node netNode = getNodeOrNull("/root/NetworkManager");
        if (netNode instanceof com.openworld.net.NetworkManager net)
            net.broadcastWaypoint(id, true, worldPos);
    }

    /** Clear this player's GPS waypoint (and tell teammates). */
    public void clearWaypoint() {
        String id = waypointKey();
        if (id.isEmpty()) return;
        com.openworld.game.WaypointStore.clear(id);
        Node netNode = getNodeOrNull("/root/NetworkManager");
        if (netNode instanceof com.openworld.net.NetworkManager net)
            net.broadcastWaypoint(id, false, godot.core.Vector3.Companion.getZERO());
    }

    /** This player's current waypoint, or null if none. */
    public godot.core.Vector3 getWaypoint() {
        return com.openworld.game.WaypointStore.get(waypointKey());
    }
}
