#!/usr/bin/env python3
"""Generate the Godot toon uniforms from the one owner of the look (PLAN.md 6.10).

    python3 tools/build_toon.py [--check]

assets/vfx/toon/toon_params.json -> assets/vfx/toon/toon_params.gdshaderinc (uniform declarations with the
JSON's values as defaults). The Blender twin is blender/tools/build_toon_nodegroup.py, reading the same file.
--check exits 1 when the include is stale.
"""
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "assets/vfx/toon/toon_params.json")
OUT = os.path.join(ROOT, "assets/vfx/toon/toon_params.gdshaderinc")


def render(p):
    t = p["shade_tint"]
    lines = ["// GENERATED by tools/build_toon.py from toon_params.json -- edit the JSON, not this.",
             f"uniform float shade_threshold : hint_range(-1.0, 1.0) = {p['shade_threshold']};",
             f"uniform float shade_softness : hint_range(0.0, 0.5) = {p['shade_softness']};",
             f"uniform vec3 shade_tint = vec3({t[0]}, {t[1]}, {t[2]});",
             f"uniform float specular_threshold : hint_range(0.0, 1.0) = {p['specular_threshold']};",
             f"uniform float specular_softness : hint_range(0.0, 0.2) = {p['specular_softness']};",
             f"uniform float specular_strength : hint_range(0.0, 2.0) = {p['specular_strength']};",
             f"uniform float rim_width : hint_range(0.0, 1.0) = {p['rim_width']};",
             f"uniform float rim_softness : hint_range(0.0, 0.5) = {p['rim_softness']};",
             f"uniform float rim_strength : hint_range(0.0, 2.0) = {p['rim_strength']};",
             f"uniform float face_flatten : hint_range(0.0, 1.0) = {p['face_flatten']};",
             ""]
    return "\n".join(lines)


def main():
    text = render(json.load(open(SRC)))
    old = open(OUT).read() if os.path.exists(OUT) else None
    if "--check" in sys.argv:
        if old != text:
            print("[toon] STALE: run python3 tools/build_toon.py")
            sys.exit(1)
        print("[toon] up to date")
        return
    if old != text:
        open(OUT, "w").write(text)
    print("[toon] wrote", os.path.relpath(OUT, ROOT))


if __name__ == "__main__":
    main()
