package com.character;

import godot.annotation.Export;
import godot.annotation.RegisterClass;
import godot.annotation.RegisterFunction;
import godot.annotation.RegisterProperty;
import godot.api.*;
import godot.core.StringName;
import godot.core.Vector3;

/**
 * AI-controlled character body — hardware and sensing only.
 *
 * Input is generated by the CharacterController child node (the "brain").
 * This class owns only body capabilities: navigation, line-of-sight, aim
 * hardware, weapon selection, and patrol geometry.
 *
 * Equivalent to L4D's CTerrorPlayer body when driven by SurvivorBot.
 * Swapping the CharacterController child for a PlayerController or
 * NetworkController changes who controls the body without touching this class.
 */
@RegisterClass(className = "AICharacter")
public class AICharacter extends Character {

    public static final float EYE_HEIGHT       = 1.4f;
    public static final float TARGET_BODY_HEIGHT = 0.9f;

    // ── Inspector-tunable body properties ─────────────────────────────────────
    @Export @RegisterProperty public float  detectionRange       = 120.0f;
    @Export @RegisterProperty public float  aimPitchMin          = -55.0f;
    @Export @RegisterProperty public float  aimPitchMax          =  75.0f;
    @Export @RegisterProperty public float  attackRange          = 150.0f;
    @Export @RegisterProperty public float  patrolRadius         =  80.0f;
    @Export @RegisterProperty public Area3D ammoRefill;

    @Export @RegisterProperty public float hitChance            = 0.9f;
    @Export @RegisterProperty public float reactionTime         = 0.1f;
    @Export @RegisterProperty public float aimScatterRadius     = 1.5f;
    @Export @RegisterProperty public float strafeChangeDuration = 1f;
    @Export @RegisterProperty public float suppressionDuration  = 1.5f;

    private static final float AMMO_REFILL_ARRIVAL_THRESHOLD = 1.5f;

    // ── AI hardware ───────────────────────────────────────────────────────────
    private NavigationAgent3D navAgent;
    private RayCast3D         sightRay;

    // ── Body state ────────────────────────────────────────────────────────────
    private boolean   isDead        = false;
    private Character currentTarget;
    private Vector3   spawnPosition;

    // ── Lifecycle ─────────────────────────────────────────────────────────────
    @RegisterFunction
    @Override
    public void _ready() {
        useWeaponSpread = false;
        super._ready();
        navAgent = (NavigationAgent3D) getNode("NavigationAgent3D");
        sightRay = (RayCast3D) getNode("CameraRoot/Yaw/Pitch/Pivot/SpringArm/Camera/SightRay");

        for (int i = 0; i < physicalBoneSimulator.getChildCount(); i++) {
            Node child = physicalBoneSimulator.getChild(i);
            if (child instanceof PhysicalBone3D bone) sightRay.addException(bone);
        }
        spawnPosition = new Vector3(getGlobalPosition());
    }

    // ── Controller access ─────────────────────────────────────────────────────
    public boolean isDead() { return isDead; }

    public CharacterController getCharacterController() {
        return (controller instanceof CharacterController c) ? c : null;
    }

    // ── Sensing / target discovery ────────────────────────────────────────────

    public Character getTarget()  { return currentTarget; }
    public void      clearTarget() { currentTarget = null; }

    public NavigationAgent3D getNavAgent() { return navAgent; }

    /**
     * Scans the "characters" group for the nearest hostile character.
     * Result is cached in currentTarget; called lazily by canSeeTarget().
     */
    private Character discoverTarget() {
        String myFaction = characterInfo != null ? characterInfo.faction : Faction.ENEMY;
        float closestDist = Float.MAX_VALUE;
        Character closest = null;
        for (Node node : getTree().getNodesInGroup(new StringName("characters"))) {
            if (!(node instanceof Character c) || c == this) continue;
            String tf = c.characterInfo != null ? c.characterInfo.faction : Faction.NEUTRAL;
            if (!Faction.areHostile(myFaction, tf)) continue;
            float dist = (float) getGlobalPosition().distanceTo(c.getGlobalPosition());
            if (dist < closestDist) { closestDist = dist; closest = c; }
        }
        return closest;
    }

    /** Discovers a target if none set, then checks detectionRange and LoS. */
    public boolean canSeeTarget() {
        if (currentTarget == null) currentTarget = discoverTarget();
        if (currentTarget == null) return false;
        float dist = (float) getGlobalPosition().distanceTo(currentTarget.getGlobalPosition());
        if (dist > detectionRange) return false;
        return hasLineOfSight();
    }

    /** Pure LoS check — never moves the camera. */
    public boolean hasLineOfSight() {
        if (currentTarget == null || sightRay == null) return false;
        Vector3 bodyPos = ((Node3D) currentTarget.getNode(
                "MeshRoot/Model/Godot_Chan_Stealth/Skeleton3D/PhysicalBoneSimulator3D/Physical Bone neck_01"))
                .getGlobalPosition();
        sightRay.setTargetPosition(sightRay.toLocal(bodyPos));
        sightRay.forceRaycastUpdate();
        if (!sightRay.isColliding()) return false;
        return sightRay.getCollider() instanceof Node3D
                && ((Node3D) sightRay.getCollider()).getOwner() == currentTarget;
    }

    // ── Aim hardware ──────────────────────────────────────────────────────────

    public void aimAtPosition(Vector3 target, double delta) {
        if (!(cameraRoot instanceof AICameraController cam) || target == null) return;
        cam.setAimTarget(target);
    }

    public void clearCameraAimTarget() {
        if (cameraRoot instanceof AICameraController cam) cam.clearAimTarget();
    }

    public void snapAimRay(Vector3 worldTarget) {
        if (aimRay == null || worldTarget == null) return;
        aimRay.setTargetPosition(aimRay.toLocal(worldTarget));
        aimRay.forceRaycastUpdate();
    }

    /** Hit: aims at target neck. Miss: random scatter scaling with distance. */
    public Vector3 computeAimTarget(boolean isHit, float hDist) {
        Vector3 base = ((Node3D) currentTarget.getNode(
                "MeshRoot/Model/Godot_Chan_Stealth/Skeleton3D/PhysicalBoneSimulator3D/Physical Bone neck_01"))
                .getGlobalPosition();
        if (isHit) return base;
        float maxOffset = aimScatterRadius * (hDist / 10f);
        float offset    = godot.global.GD.randf() * maxOffset;
        float angle     = godot.global.GD.randf() * (float) (Math.PI * 2.0);
        return base.plus(new Vector3(
                offset * (float) Math.cos(angle),
                offset * (float) Math.sin(angle), 0f));
    }

    // ── Weapon / ammo ─────────────────────────────────────────────────────────

    public int selectBestWeapon() {
        if (weaponController == null) return -1;
        int bestIndex = -1;
        float bestDamage = -1f;
        for (int i = 0; i < weaponController.getSlotCount(); i++) {
            if (!weaponController.hasAmmoForWeapon(i)) continue;
            WeaponItem s = weaponController.getWeaponStats(i);
            if (s != null && s.damage > bestDamage) { bestDamage = s.damage; bestIndex = i; }
        }
        return bestIndex;
    }

    public boolean hasAnyAmmo() { return selectBestWeapon() >= 0; }

    public boolean isAtAmmoRefill() {
        if (ammoRefill == null) return false;
        return (float) getGlobalPosition().distanceTo(ammoRefill.getGlobalPosition())
                <= AMMO_REFILL_ARRIVAL_THRESHOLD;
    }

    // ── Navigation ────────────────────────────────────────────────────────────

    public void setNextPatrolTarget() {
        float angle = godot.global.GD.randf() * (float) Math.PI * 2.0f;
        float dist  = godot.global.GD.randf() * patrolRadius;
        navAgent.setTargetPosition(spawnPosition.plus(new Vector3(
                (float) Math.cos(angle) * dist, 0.0f, (float) Math.sin(angle) * dist)));
    }

    // ── Signal receivers ──────────────────────────────────────────────────────

    /** Connected to Health.damaged signal in AICharacter.tscn. */
    @RegisterFunction
    public void onEnemyDamaged(float amount) {
        CharacterController ctrl = getCharacterController();
        if (ctrl != null) ctrl.onDamagedByAttacker(currentTarget);
    }

    @RegisterFunction
    @Override
    public void onDied() {
        isDead = true;
        super.onDied();
    }
}
