package com.character;

import godot.annotation.Export;
import godot.annotation.RegisterClass;
import godot.annotation.RegisterFunction;
import godot.annotation.RegisterProperty;
import godot.api.*;
import godot.core.StringName;
import godot.core.Vector3;

/**
 * AI-controlled character body — hardware and sensing only.
 *
 * Input is generated by the CharacterController child node (the "brain").
 * This class owns only body capabilities: navigation, line-of-sight, aim
 * hardware, weapon selection, and patrol geometry.
 *
 * Equivalent to L4D's CTerrorPlayer body when driven by SurvivorBot.
 * Swapping the CharacterController child for a PlayerController or
 * NetworkController changes who controls the body without touching this class.
 */
@RegisterClass(className = "AICharacter")
public class AICharacter extends Character {

    public static final float EYE_HEIGHT       = 1.4f;
    public static final float TARGET_BODY_HEIGHT = 0.9f;

    // ── Inspector-tunable body properties ─────────────────────────────────────
    @Export @RegisterProperty public float  detectionRange       = 120.0f;
    @Export @RegisterProperty public float  aimPitchMin          = -55.0f;
    @Export @RegisterProperty public float  aimPitchMax          =  75.0f;
    @Export @RegisterProperty public float  attackRange          = 150.0f;
    @Export @RegisterProperty public float  patrolRadius         =  80.0f;
    @Export @RegisterProperty public Area3D ammoRefill;

    /**
     * Which body part the AI tries to hit on a successful accuracy roll.
     * Maps directly to the damage multipliers in Health.getDamageMultiplier():
     *   HEAD  → head_2        (4.0× — hardest, one-shot potential)
     *   CHEST → spine_03       (1.0× — balanced)
     *   BODY  → spine_01       (0.75× — forgiving)
     *   LEGS  → thigh_l/r      (0.5× — easiest)
     * On a miss the shot scatters by aimScatterRadius regardless of body part.
     */
    @Export @RegisterProperty public String aimBodyPart         = "CHEST";

    @Export @RegisterProperty public float hitChance            = 0.5f;
    @Export @RegisterProperty public float reactionTime         = 0.6f;
    @Export @RegisterProperty public float aimScatterRadius     = 2.5f;
    @Export @RegisterProperty public float strafeChangeDuration = 1f;
    @Export @RegisterProperty public float suppressionDuration  = 1.5f;

    /** How long (seconds) the AI stops after each shot before resuming strafe. */
    @Export @RegisterProperty public float shootStillDuration   = 0.25f;
    /**
     * Fraction of hitChance lost when moving at full walk speed (0 = no penalty, 1 = zero accuracy).
     * At half walk speed the penalty is halved. Stationary AI always fires at full hitChance.
     */
    @Export @RegisterProperty public float moveAccuracyPenalty  = 0.75f;

    /**
     * When true, the AI crouches once it has LoS, is in its firing position,
     * and has completed its reaction delay.  Returns to UPRIGHT when repositioning
     * or losing sight.  Trade-off: slower strafing, better effective accuracy.
     */
    @Export @RegisterProperty public boolean useCombatCrouch = true;

    private static final float  AMMO_REFILL_ARRIVAL_THRESHOLD = 1.5f;

    // ── Sensor throttle constants ─────────────────────────────────────────────
    // Cached once — avoids a StringName allocation on every group scan.
    private static final StringName CHARACTERS_GROUP     = new StringName("characters");
    // Target rediscovery interval: new enemies can't teleport in, 0.4 s is imperceptible.
    private static final double     TARGET_SCAN_INTERVAL = 0.4;
    // LoS cache interval: ~3 physics frames at 60 Hz — no gameplay impact.
    private static final double     LOS_CACHE_INTERVAL   = 0.05;

    // ── AI hardware ───────────────────────────────────────────────────────────
    private NavigationAgent3D  navAgent;
    private AICameraController aiCamera;

    // ── Body state ────────────────────────────────────────────────────────────
    private boolean   isDead        = false;
    private Character currentTarget;
    private Vector3   spawnPosition;

    // ── Sensor cache ─────────────────────────────────────────────────────────
    private double    targetScanTimer     = 0.0;
    private double    losCacheTimer       = 0.0;
    private boolean   cachedLoS           = false;
    // Bone nodes resolved once per target — priority-ordered by aimBodyPart so
    // the LoS walk naturally expresses bot difficulty without extra logic.
    private Character cachedTargetForBone = null;
    private Node3D[]  cachedBoneNodes     = null;   // priority list: [preferred, fallback...]
    private Node3D    cachedVisibleBone   = null;   // first bone confirmed exposed in last check

    // ── Lifecycle ─────────────────────────────────────────────────────────────
    @RegisterFunction
    @Override
    public void _ready() {
        useWeaponSpread = false;
        super._ready();
        navAgent = (NavigationAgent3D) getNode("NavigationAgent3D");
        if (cameraRoot instanceof AICameraController ac) aiCamera = ac;

        // aimRay serves as the LoS ray (same camera origin as the former SightRay).
        // Bone exceptions are already added by Character._ready() via aimRayPath.
        spawnPosition = new Vector3(getGlobalPosition());

        // Stagger each AI's scan timers so every bot doesn't expire on the same frame.
        targetScanTimer = godot.global.GD.randfRange(0f, (float) TARGET_SCAN_INTERVAL);
        losCacheTimer   = godot.global.GD.randfRange(0f, (float) LOS_CACHE_INTERVAL);

        // Start the FSM now that all body hardware is ready.
        // AIController._ready() intentionally leaves currentState null so this
        // is the only place the FSM starts.
        if (controller instanceof AIController aiCtrl) aiCtrl.start();
    }

    // ── Controller access ─────────────────────────────────────────────────────
    public boolean isDead() { return isDead; }

    public CharacterController getCharacterController() {
        return (controller instanceof CharacterController c) ? c : null;
    }

    // ── Sensing / target discovery ────────────────────────────────────────────

    public Character getTarget()  { return currentTarget; }
    public void      clearTarget() { currentTarget = null; }

    public NavigationAgent3D getNavAgent() { return navAgent; }

    /** Full group scan for nearest live hostile. Called at most once per TARGET_SCAN_INTERVAL. */
    private Character discoverTarget() {
        String myFaction = characterInfo != null ? characterInfo.faction : Faction.ENEMY;
        float closestDist = Float.MAX_VALUE;
        Character closest = null;
        for (Node node : getTree().getNodesInGroup(CHARACTERS_GROUP)) {
            if (!(node instanceof Character c) || c == this || !c.isAlive()) continue;
            String tf = c.characterInfo != null ? c.characterInfo.faction : Faction.NEUTRAL;
            if (!Faction.areHostile(myFaction, tf)) continue;
            float dist = (float) getGlobalPosition().distanceTo(c.getGlobalPosition());
            if (dist < closestDist) { closestDist = dist; closest = c; }
        }
        return closest;
    }

    /**
     * Throttled target refresh — runs the full group scan at most once per
     * TARGET_SCAN_INTERVAL seconds.  Clears the LoS and bone caches whenever
     * the closest hostile changes so stale data is never used.
     */
    public void refreshTarget(double delta) {
        targetScanTimer -= delta;
        if (targetScanTimer > 0) return;
        targetScanTimer = TARGET_SCAN_INTERVAL;
        Character previous = currentTarget;
        currentTarget = discoverTarget();
        if (currentTarget != previous) {
            cachedTargetForBone = null;
            cachedBoneNodes     = null;
            cachedVisibleBone   = null;
            cachedLoS           = false;
            losCacheTimer       = 0;
        }
    }

    /**
     * Throttled visibility check for patrol detection.  Shares the same scan
     * timer as refreshTarget so the two never double-scan on the same frame.
     */
    public boolean canSeeTarget(double delta) {
        targetScanTimer -= delta;
        if (targetScanTimer <= 0) {
            targetScanTimer = TARGET_SCAN_INTERVAL;
            Character previous = currentTarget;
            currentTarget = discoverTarget();
            if (currentTarget != previous) {
                cachedTargetForBone = null;
                cachedBoneNodes     = null;
                cachedVisibleBone   = null;
                cachedLoS           = false;
                losCacheTimer       = 0;
            }
        }
        if (currentTarget == null) return false;
        float dist = (float) getGlobalPosition().distanceTo(currentTarget.getGlobalPosition());
        if (dist > detectionRange) return false;
        return hasLineOfSight(delta);
    }

    /**
     * Builds the priority-ordered bone list for the current target based on
     * aimBodyPart.  Called once per target; the result is cached in cachedBoneNodes.
     *
     * Priority order expresses difficulty:
     *   HEAD  → [head_2, spine_03, spine_01]  hardest target first, body fallbacks
     *   CHEST → [spine_03, spine_01, head_2]  centre-mass first, head is last resort
     *   BODY  → [spine_01, spine_03, thigh_l]  lower torso first, escalates upward
     *   LEGS  → [thigh_l,  thigh_r,  spine_01] legs first, torso only if both legs covered
     */
    private void resolveTargetBones() {
        cachedTargetForBone = currentTarget;
        cachedVisibleBone   = null;
        String[] names;
        switch (aimBodyPart.toUpperCase()) {
            case "HEAD":  names = new String[]{"head_2",  "spine_03", "spine_01"}; break;
            case "BODY":  names = new String[]{"spine_01", "spine_03", "thigh_l"};  break;
            case "LEGS":  names = new String[]{"thigh_l",  "thigh_r",  "spine_01"}; break;
            default:      names = new String[]{"spine_03", "spine_01", "head_2"};  break; // CHEST
        }
        cachedBoneNodes = new Node3D[names.length];
        for (int i = 0; i < names.length; i++) {
            cachedBoneNodes[i] = currentTarget.getPhysicalBoneNode(names[i]);
        }
    }

    /**
     * LoS check with a short result cache (~3 frames at 60 Hz).
     * Walks the priority bone list in order — stops at the first exposed bone
     * and stores it in cachedVisibleBone so getAimBonePosition() can use it.
     * At most 3 forceRaycastUpdate calls per LOS_CACHE_INTERVAL in the worst case
     * (all bones behind cover); typically 1 call when the preferred bone is clear.
     */
    public boolean hasLineOfSight(double delta) {
        if (currentTarget == null || aimRay == null) return false;
        losCacheTimer -= delta;
        if (losCacheTimer > 0) return cachedLoS;
        losCacheTimer = LOS_CACHE_INTERVAL;
        if (currentTarget != cachedTargetForBone) resolveTargetBones();
        if (cachedBoneNodes == null) { cachedLoS = false; return false; }
        cachedVisibleBone = null;
        for (Node3D bone : cachedBoneNodes) {
            if (bone == null) continue;
            aimRay.setTargetPosition(aimRay.toLocal(bone.getGlobalPosition()));
            aimRay.forceRaycastUpdate();
            if (aimRay.isColliding()
                    && aimRay.getCollider() instanceof Node3D n
                    && currentTarget.isAncestorOf(n)) {
                cachedVisibleBone = bone;
                cachedLoS = true;
                return true;
            }
        }
        cachedLoS = false;
        return false;
    }

    // ── Aim hardware ──────────────────────────────────────────────────────────

    public void aimAtPosition(Vector3 target, double delta) {
        if (aiCamera == null || target == null) return;
        aiCamera.setAimTarget(target);
    }

    public void clearCameraAimTarget() {
        if (aiCamera != null) aiCamera.clearAimTarget();
    }

    /**
     * AI-accessible direct stance transition.  Checks ceiling blocking and updates
     * movement speed — both skipped in the base-class vehicle path.
     * No antispam timer, no toggle: the AI drives stance directly.
     */
    public void forceSetStance(StanceName stanceName) {
        if (isStanceBlocked(stanceName)) return;
        super.forceSetStance(stanceName);
        setMovementState(currentMovementType);
    }

    public void snapAimRay(Vector3 worldTarget) {
        if (aimRay == null || worldTarget == null) return;
        aimRay.setTargetPosition(aimRay.toLocal(worldTarget));
        aimRay.forceRaycastUpdate();
    }

    /**
     * Returns the world position to aim at on the current target.
     * Prefers the bone last confirmed exposed by hasLineOfSight() — no additional
     * raycast needed since we already know it's clear.  Falls back to the first
     * (preferred) bone in the priority list if the LoS result is stale.
     */
    public Vector3 getAimBonePosition() {
        if (cachedVisibleBone != null) return cachedVisibleBone.getGlobalPosition();
        if (cachedBoneNodes != null && cachedBoneNodes.length > 0 && cachedBoneNodes[0] != null)
            return cachedBoneNodes[0].getGlobalPosition();
        Node3D headBone = currentTarget.getPhysicalBoneNode("head_2");
        return headBone != null ? headBone.getGlobalPosition() : currentTarget.getGlobalPosition();
    }

    /**
     * hitChance scaled down by current velocity — stationary = full accuracy,
     * walking at reference speed (4 m/s) = hitChance × (1 − moveAccuracyPenalty).
     * The stillTimer in AttackState keeps velocity near zero at fire time so the
     * AI naturally fires at full hitChance after its stop-to-shoot pause.
     */
    public float computeEffectiveHitChance() {
        float speed       = (float) getVelocity().length();
        float moveFactor  = Math.min(1.0f, speed / 4.0f);
        return hitChance * (1.0f - moveFactor * moveAccuracyPenalty);
    }

    /**
     * Hit: returns exact aim-bone position. Miss: random scatter combining two terms:
     *   aimScatterRadius × (hDist/10)  — per-AI tuning knob, scales with distance
     *   hDist × tan(weaponSpreadDeg)   — live weapon physics (bloom, stance, velocity)
     * The weapon term means burst fire degrades AI accuracy just like it does for the
     * player, and a shotgun-AI is naturally less accurate than a sniper-AI at range.
     */
    public Vector3 computeAimTarget(boolean isHit, float hDist) {
        Vector3 base = getAimBonePosition();
        if (isHit) return base;
        float weaponSpreadM = 0f;
        if (weaponController != null) {
            float spreadDeg = weaponController.getCurrentSpreadDeg();
            weaponSpreadM = hDist * (float) Math.tan(Math.toRadians(spreadDeg));
        }
        float maxOffset = aimScatterRadius * (hDist / 10f) + weaponSpreadM;
        float offset    = godot.global.GD.randf() * maxOffset;
        float angle     = godot.global.GD.randf() * (float) (Math.PI * 2.0);
        return base.plus(new Vector3(
                offset * (float) Math.cos(angle),
                offset * (float) Math.sin(angle), 0f));
    }

    // ── Weapon / ammo ─────────────────────────────────────────────────────────

    public int selectBestWeapon() {
        if (weaponController == null) return -1;
        int bestIndex = -1;
        float bestDamage = -1f;
        for (int i = 0; i < weaponController.getSlotCount(); i++) {
            if (!weaponController.hasAmmoForWeapon(i)) continue;
            WeaponItem s = weaponController.getWeaponStats(i);
            if (s != null && s.damage > bestDamage) { bestDamage = s.damage; bestIndex = i; }
        }
        return bestIndex;
    }

    public boolean hasAnyAmmo() { return selectBestWeapon() >= 0; }

    public boolean isAtAmmoRefill() {
        if (ammoRefill == null) return false;
        return (float) getGlobalPosition().distanceTo(ammoRefill.getGlobalPosition())
                <= AMMO_REFILL_ARRIVAL_THRESHOLD;
    }

    // ── Navigation ────────────────────────────────────────────────────────────

    public void setNextPatrolTarget() {
        float angle = godot.global.GD.randf() * (float) Math.PI * 2.0f;
        float dist  = godot.global.GD.randf() * patrolRadius;
        navAgent.setTargetPosition(spawnPosition.plus(new Vector3(
                (float) Math.cos(angle) * dist, 0.0f, (float) Math.sin(angle) * dist)));
    }

    // ── Signal receivers ──────────────────────────────────────────────────────

    /** Connected to Health.damaged signal in AICharacter.tscn. */
    @RegisterFunction
    public void onEnemyDamaged(float amount) {
        CharacterController ctrl = getCharacterController();
        if (ctrl != null) ctrl.onDamagedByAttacker(currentTarget);
    }

    @RegisterFunction
    @Override
    public void onDied() {
        isDead = true;
        super.onDied();
    }
}
