package com.character;

import com.game.EventBus;
import com.vehicle.Vehicle;
import godot.annotation.RegisterClass;
import godot.annotation.RegisterFunction;
import godot.api.Node;

/**
 * Human-controlled character body.
 *
 * Input is generated by the PlayerController child node, not here.
 * This class owns only player-specific body hardware: the aimRay self-exclusion
 * (prevents self-hits), AimStayTimer node (used by PlayerController), the
 * EventBus death notification, and vehicle enter/exit logic.
 *
 * nearbyVehicle is set/cleared by Vehicle.onEntranceBodyEntered/Exited when
 * the player walks into or out of a vehicle's entrance trigger zone. When the
 * player presses "use" (enterExit in the command) and nearbyVehicle is set,
 * applyInput delegates to Vehicle.tryEnter(this) rather than processing normal
 * character inputs.
 */
@RegisterClass
public class Player extends Character {

    /** Set by the nearest Vehicle's EntranceArea when the player is in range. */
    public Vehicle nearbyVehicle;

    @RegisterFunction
    @Override
    public void _ready() {
        super._ready();
        aimRay.addException(this);
    }

    @Override
    protected void applyInput(UserCommand cmd, double delta) {
        if (cmd.enterExit && nearbyVehicle != null) {
            nearbyVehicle.tryEnter(this);
            return; // skip normal inputs this tick
        }
        super.applyInput(cmd, delta);
    }

    @RegisterFunction
    @Override
    public void onDied() {
        setProcessInput(false);
        super.onDied();
        Node eventBusNode = getNodeOrNull("/root/EventBus");
        if (eventBusNode instanceof EventBus bus) bus.playerDied.emit();
    }
}
