package com.character;

import com.game.EventBus;
import godot.annotation.RegisterClass;
import godot.annotation.RegisterFunction;
import godot.api.Node;

/**
 * Human-controlled character body.
 *
 * Input is generated by the PlayerController child node, not here.
 * This class owns only player-specific body hardware: the aimRay self-exclusion
 * (prevents self-hits), AimStayTimer node (used by PlayerController), and the
 * EventBus death notification.
 */
@RegisterClass
public class Player extends Character {

    @RegisterFunction
    @Override
    public void _ready() {
        super._ready();
        aimRay.addException(this);
    }

    @RegisterFunction
    @Override
    public void onDied() {
        setProcessInput(false);
        super.onDied();
        Node eventBusNode = getNodeOrNull("/root/EventBus");
        if (eventBusNode instanceof EventBus bus) bus.playerDied.emit();
    }
}
